#!/usr/bin/env python3
"""Plot UAV TN/NTN switching xApp AI model comparison.

The script reads the model-comparison CSV generated by
train-uav-switching-xapp-ai.py and produces a LaTeX-style figure showing
classification quality and inference latency.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


MODEL_LABELS = {
    "decision_tree": "DT",
    "random_forest": "RF",
    "gradient_boosting": "HGB",
    "xgboost": "XGBoost",
    "neural_network": "NN",
}


def load_style() -> None:
    style_path = Path("./latex_style.mplstyle")
    if not style_path.exists():
        style_path = Path(__file__).resolve().parents[3] / "latex_style.mplstyle"
    if style_path.exists():
        plt.style.use(style_path)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--input",
        type=Path,
        default=Path("results/ai/uav-switching-xapp-ai-dataset-v2/uav_switching_xapp_model_comparison.csv"),
        help="Model comparison CSV generated by train-uav-switching-xapp-ai.py",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("docs/figures/figure_ai_switching_model_comparison.png"),
        help="Output figure path",
    )
    parser.add_argument(
        "--pdf",
        type=Path,
        default=Path("docs/figures/figure_ai_switching_model_comparison.pdf"),
        help="Optional PDF output path",
    )
    args = parser.parse_args()

    load_style()
    data = pd.read_csv(args.input)
    data["label"] = data["model"].map(MODEL_LABELS).fillna(data["model"])
    data = data.sort_values("macro_f1", ascending=False).reset_index(drop=True)

    x = np.arange(len(data))
    width = 0.34

    fig, ax1 = plt.subplots(figsize=(9.8, 5.05))
    ax2 = ax1.twinx()

    bars1 = ax1.bar(
        x - width / 2,
        data["macro_f1"] * 100.0,
        width,
        label="Macro-F1",
        color="#4C78A8",
        edgecolor="black",
        linewidth=0.5,
    )
    bars2 = ax1.bar(
        x + width / 2,
        data["accuracy"] * 100.0,
        width,
        label="Accuracy",
        color="#72B7B2",
        edgecolor="black",
        linewidth=0.5,
    )
    ax2.plot(
        x,
        data["inference_ms_per_sample"],
        color="#E45756",
        marker="o",
        linewidth=1.8,
        label="Inference time",
    )

    ax1.set_xlabel("AI model", fontsize=20)
    ax1.set_ylabel("Score (\\%)", fontsize=20)
    ax2.set_ylabel("Inference time (ms)", fontsize=20, labelpad=12)
    ax1.set_xticks(x)
    ax1.set_xticklabels(data["label"], fontsize=18)
    ax1.set_ylim(90, 96)
    ax2.set_ylim(0, max(0.08, data["inference_ms_per_sample"].max() * 1.25))
    ax1.tick_params(axis="y", labelsize=16)
    ax2.tick_params(axis="y", labelsize=16)
    ax1.grid(True, axis="y", linestyle="--", alpha=0.45)
    ax2.grid(False)

    # Annotate the selected model.
    rf_idx = data.index[data["model"] == "random_forest"]
    if len(rf_idx) > 0:
        idx = int(rf_idx[0])
        ax1.annotate(
            "selected",
            xy=(idx - width / 2, data.loc[idx, "macro_f1"] * 100.0),
            xytext=(idx - 0.40, 95.25),
            arrowprops=dict(arrowstyle="->", color="black", linewidth=0.8),
            fontsize=13,
        )

    handles1, labels1 = ax1.get_legend_handles_labels()
    handles2, labels2 = ax2.get_legend_handles_labels()
    ax1.legend(handles1 + handles2, labels1 + labels2, loc="lower left", ncol=3, frameon=True, fontsize=13)

    note_ax = fig.add_axes([0.21, 0.082, 0.58, 0.082])
    note_ax.axis("off")
    note_ax.text(0.02, 0.68, "DT: Decision Tree", ha="left", va="center", fontsize=13.5)
    note_ax.text(0.58, 0.68, "RF: Random Forest", ha="left", va="center", fontsize=13.5)
    note_ax.text(0.02, 0.20, "HGB: Hist. Gradient Boosting", ha="left", va="center", fontsize=13.5)
    note_ax.text(0.58, 0.20, "NN: Neural Network", ha="left", va="center", fontsize=13.5)

    args.output.parent.mkdir(parents=True, exist_ok=True)
    fig.subplots_adjust(left=0.095, right=0.865, bottom=0.29, top=0.955)
    fig.savefig(args.output, dpi=300)
    fig.savefig(args.pdf)
    print(f"[saved] {args.output}")
    print(f"[saved] {args.pdf}")


if __name__ == "__main__":
    main()
