

#ifndef ORAN_LM_NR_2_NR_RSRP_HANDOVER_H
#define ORAN_LM_NR_2_NR_RSRP_HANDOVER_H

#include "oran-data-repository.h"
#include "oran-lm.h"

#include "ns3/vector.h"

namespace ns3
{

/**
 * @ingroup oran
 *
 * Logic Module for the Near-RT RIC that issues Commands to handover from
 * an NR cell to another based on the rsrp from the UE to the gNBs.
 */
class OranLmNr2NrRsrpHandover : public OranLm
{
  protected:
    /**
     * UE related information.
     */
    struct UeInfo
    {
        uint64_t nodeId; //!< The node ID.
        uint16_t cellId; //!< The cell ID.
        uint16_t rnti;   //!< The RNTI ID.
        Vector position; //!< The physical position.
    };

    /**
     * gNB related information.
     */
    struct GnbInfo
    {
        uint64_t nodeId; //!< The node ID.
        uint16_t cellId; //!< The cell ID.
        Vector position; //!< The physical position.
    };

  public:
    /**
     * Gets the TypeId of the OranLmNr2NrRsrpHandover class.
     *
     * @return The TypeId.
     */
    static TypeId GetTypeId(void);
    /**
     * Constructor of the OranLmNr2NrRsrpHandover class.
     */
    OranLmNr2NrRsrpHandover(void);
    /**
     * Destructor of the OranLmNr2NrRsrpHandover class.
     */
    ~OranLmNr2NrRsrpHandover(void) override;
    /**
     * Runs the logic specific for this Logic Module. This will retrieve the
     * location of all NR UEs and gNBs, find the closest gNB for each UE, and if
     * this gNB is not the serving gNB, a handover Command is generated.
     *
     * @return A vector with the handover commands generated by this Logic Module.
     */
    std::vector<Ptr<OranCommand>> Run(void) override;

  private:
    /**
     * Method to get the UE information from the repository.
     *
     * @param data The data repository.
     *
     * @return A vector of UE Information structures.
     */
    std::vector<OranLmNr2NrRsrpHandover::UeInfo> GetUeInfos(Ptr<OranDataRepository> data) const;
    /**
     * Method to get the gNB information from the repository.
     *
     * @param data The data repository.
     *
     * @return A vector of gNB Information structures.
     */
    std::vector<OranLmNr2NrRsrpHandover::GnbInfo> GetGnbInfos(Ptr<OranDataRepository> data) const;
    /**
     * Method with the logic to get the distance between UEs and gNBs
     * and generate Handover Commands if needed.
     *
     * @param data The data repository.
     * @param ueInfos A vector with the UE information.
     * @param gnbInfos A vector with the gNB information.
     *
     * @return A vector with the handover commands generated.
     */
    std::vector<Ptr<OranCommand>> GetHandoverCommands(
        Ptr<OranDataRepository> data,
        std::vector<OranLmNr2NrRsrpHandover::UeInfo> ueInfos,
        std::vector<OranLmNr2NrRsrpHandover::GnbInfo> gnbInfos) const;

    double m_rsrpThreshold;
}; // class OranLmNr2NrRsrpHandover

} // namespace ns3

#endif /* ORAN_LM_NR_2_NR_DISTANCE_HANDOVER_H */
